<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    //protected $guarded=[];
   // protected $fillable = ['title','content','thumbnail','views','featured','user_id'];

//    public function getRouteKeyName()
//    {
//        return 'title'; // TODO: Change the autogenerated stub
//    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }


}
